# for gsaint.py
method: random # try "bayes" later
metric:
  goal: maximize
  name: score
parameters:
  out_channels: # Model parameters
    values: [10, 14, 16]
  hidden_channels:
    values: [4, 8, 16]
  lr:
    values: [0.1, 0.01, 0.001, 0.0001]
  batch_size: # RandomWalk parameters
    values: [8, 16, 32, 64, 128, 256]
  walk_lengths: 
    values: [10, 20, 50, 100, 150, 200]
  num_steps:
    values: [10, 20, 30]
  sample_coverages:
    values: [50, 100, 150, 200, 250]